// : Generated by xaf-index-generator :

export { default as SocialBadge } from './SocialBadge'
export { default as SocialLink } from './SocialLink'
export { default as SocialWrap } from './SocialWrap'